esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  comment: ${device_comment}
  name_add_mac_suffix: false
  min_version: 2025.5.0
  project:
    name: nikalexis.aquaguard
    version: "0.1.0"

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

logger:

api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
