i2c:
  id: i2c_bus
  sda: GPIO42
  scl: GPIO41
  scan: false
  frequency: 100kHz

pca9554:
  - id: relay_expander
    address: 0x20

light:
  - platform: esp32_rmt_led_strip
    id: status_led
    internal: true
    rgb_order: RGB
    chipset: WS2812
    pin: GPIO38
    num_leds: 1
    name: "Status LED"
    restore_mode: ALWAYS_OFF
