substitutions:
  device_name: aquaguard
  device_friendly_name: AquaGuard
  device_comment: "8-zone water consumption monitor and configurable relay shutoff controller"
  firmware_revision: "0.1.2"
  timezone: Europe/Athens

packages:
  device_base: !include packages/device_base.yaml
  hardware: !include packages/hardware.yaml
  ethernet: !include packages/ethernet.yaml
  time: !include packages/time.yaml
  web: !include packages/web.yaml
  persistence: !include packages/persistence.yaml
  scripts: !include packages/scripts.yaml
  diagnostics: !include packages/diagnostics.yaml

  zone_1: !include
    file: packages/zone.yaml
    vars:
      zone: "1"
      default_zone_name: "Zone 1"
      di_pin: GPIO4
      relay_pin: "0"

  zone_2: !include
    file: packages/zone.yaml
    vars:
      zone: "2"
      default_zone_name: "Zone 2"
      di_pin: GPIO5
      relay_pin: "1"

  zone_3: !include
    file: packages/zone.yaml
    vars:
      zone: "3"
      default_zone_name: "Zone 3"
      di_pin: GPIO6
      relay_pin: "2"

  zone_4: !include
    file: packages/zone.yaml
    vars:
      zone: "4"
      default_zone_name: "Zone 4"
      di_pin: GPIO7
      relay_pin: "3"

  zone_5: !include
    file: packages/zone.yaml
    vars:
      zone: "5"
      default_zone_name: "Zone 5"
      di_pin: GPIO8
      relay_pin: "4"

  zone_6: !include
    file: packages/zone.yaml
    vars:
      zone: "6"
      default_zone_name: "Zone 6"
      di_pin: GPIO9
      relay_pin: "5"

  zone_7: !include
    file: packages/zone.yaml
    vars:
      zone: "7"
      default_zone_name: "Zone 7"
      di_pin: GPIO10
      relay_pin: "6"

  zone_8: !include
    file: packages/zone.yaml
    vars:
      zone: "8"
      default_zone_name: "Zone 8"
      di_pin: GPIO11
      relay_pin: "7"
